"""Declarative score metadata for incrementally migrated boundary rules."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class BoundaryScoreDirection(str, Enum):
    RISK = "risk"
    BONUS = "bonus"


class BoundaryScoreSeverity(str, Enum):
    WARNING = "warning"
    ERROR = "error"


@dataclass(frozen=True, slots=True)
class BoundaryScoreRule:
    rule_id: str
    reason: str
    family: str
    direction: BoundaryScoreDirection
    weight: int
    source_languages: tuple[str, ...]
    speaker_modes: tuple[str, ...]
    required_features: tuple[str, ...]
    exclusions: tuple[str, ...] = ()

    @property
    def severity(self) -> BoundaryScoreSeverity:
        return BoundaryScoreSeverity.ERROR if self.weight >= 30 else BoundaryScoreSeverity.WARNING

    @property
    def explanation_template(self) -> str:
        return self.reason


@dataclass(frozen=True, slots=True)
class BoundaryScoreContribution:
    rule_id: str
    reason: str
    weight: int


_ENGLISH_NUMERIC_RULES = (
    BoundaryScoreRule(
        "split.boundary.english.numeric.measurement_comparative",
        "measurement separated from its comparative relation",
        "numeric",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens", "right_tokens"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.numeric.approximate_magnitude",
        "approximate magnitude separated from its numeric value",
        "numeric",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.numeric.value_unit_or_noun",
        "numeric value separated from its unit or noun",
        "numeric",
        BoundaryScoreDirection.RISK,
        30,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_case"),
        ("completed_calendar_year",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.numeric.calendar_month_year",
        "calendar month separated from its year",
        "numeric",
        BoundaryScoreDirection.RISK,
        42,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.numeric.compound_modifier",
        "numeric compound modifier separated from its head noun",
        "numeric",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.numeric.multiplier_or_unit",
        "numeric value separated from its multiplier or unit",
        "numeric",
        BoundaryScoreDirection.RISK,
        40,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.numeric.mixed_measurement",
        "mixed-number measurement split before 'and a half'",
        "numeric",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_tokens"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.numeric.range_conjunction",
        "numeric range split at conjunction",
        "numeric",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens", "right_tokens"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.numeric.model_year_vehicle_name",
        "model year separated from its vehicle name",
        "numeric",
        BoundaryScoreDirection.RISK,
        42,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens", "right_entity"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.numeric.article_model_year_vehicle_name",
        "model year separated from vehicle name",
        "numeric",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens", "right_entity"),
    ),
)

_ENGLISH_GRAMMAR_RULES = (
    BoundaryScoreRule(
        "split.boundary.english.grammar.incomplete_multiword",
        "incomplete multi-word phrase",
        "grammar",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.dangling_function_word",
        "dangling function word '{token}'",
        "grammar",
        BoundaryScoreDirection.RISK,
        32,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail",),
        ("complete_visibility_preposition",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.dangling_function_word_before_filler",
        "dangling function word '{token}' before trailing discourse filler",
        "grammar",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("semantic_left_tail",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.dangling_subject",
        "dangling subject '{token}'",
        "grammar",
        BoundaryScoreDirection.RISK,
        26,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_case"),
        ("terminal_clause", "complete_demonstrative_object"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.standalone_subject",
        "standalone subject separated from its predicate",
        "grammar",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.sentence_final_subject",
        "sentence-final subject belongs to the following predicate",
        "grammar",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.subject_before_adverbial_predicate",
        "dangling subject '{token}' before its adverbial predicate",
        "grammar",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.incomplete_predicate",
        "incomplete predicate '{token}'",
        "grammar",
        BoundaryScoreDirection.RISK,
        32,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail",),
        ("complete_does_clause",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.dangling_modifier",
        "dangling modifier '{token}'",
        "grammar",
        BoundaryScoreDirection.RISK,
        24,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_case"),
        ("complete_modifier_exception",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.dangling_modifier_strong",
        "dangling modifier '{token}'",
        "grammar",
        BoundaryScoreDirection.RISK,
        30,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_case"),
        ("complete_modifier_exception",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.dangling_attributive",
        "dangling attributive '{token}'",
        "grammar",
        BoundaryScoreDirection.RISK,
        24,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_case"),
        ("complete_own_idiom",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.determiner_head",
        "determiner separated from its '{token}' head noun",
        "grammar",
        BoundaryScoreDirection.RISK,
        30,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens", "right_case"),
        ("complete_own_idiom",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.attributive_or_comparative_modifier",
        "attributive or comparative modifier separated from its head",
        "grammar",
        BoundaryScoreDirection.RISK,
        22,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_case"),
        ("complete_predicative_adjective",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.determiner_adjective_head",
        "determiner and adjective separated from their head noun",
        "grammar",
        BoundaryScoreDirection.RISK,
        40,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.open_complement",
        "open complement after '{token}'",
        "grammar",
        BoundaryScoreDirection.RISK,
        26,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_case"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.open_complement_strong",
        "open complement after '{token}'",
        "grammar",
        BoundaryScoreDirection.RISK,
        30,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_case"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.single_word_completion",
        "single-word completion stranded in the next subtitle",
        "grammar",
        BoundaryScoreDirection.RISK,
        52,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens", "right_tokens", "right_case"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.dependent_phrase",
        "dependent phrase beginning with '{token}'",
        "grammar",
        BoundaryScoreDirection.RISK,
        30,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens", "right_head"),
        ("fixed_phrase", "ease_of_use_phrase", "terminal_left"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.relative_clause",
        "relative clause '{token}' separated from its antecedent",
        "grammar",
        BoundaryScoreDirection.RISK,
        30,
        ("en",),
        ("monologue", "dialogue"),
        ("left_clause", "right_head"),
        ("that_complement",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.dependent_adverbial_clause",
        "dependent adverbial clause beginning with '{token}'",
        "grammar",
        BoundaryScoreDirection.RISK,
        26,
        ("en",),
        ("monologue", "dialogue"),
        ("left_terminal", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.entity.proper_name",
        "proper name split between adjacent tokens",
        "entity",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_entity"),
        ("ordinary_sentence_start",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.subject_auxiliary",
        "subject and auxiliary stranded at '{token}'",
        "grammar",
        BoundaryScoreDirection.RISK,
        30,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_case"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.filler_noun_modifier",
        "filler separated from the noun it modifies",
        "grammar",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens", "right_case"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.participle_complement",
        "participle separated from its complement",
        "grammar",
        BoundaryScoreDirection.RISK,
        28,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_head"),
        ("determiner_preceded_participle",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.coordinated_noun_phrase",
        "coordinated noun phrase split at conjunction",
        "grammar",
        BoundaryScoreDirection.RISK,
        24,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens", "right_tokens"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.coordinated_noun_phrase_contextual",
        "coordinated noun phrase split at conjunction",
        "grammar",
        BoundaryScoreDirection.RISK,
        32,
        ("en",),
        ("monologue", "dialogue"),
        ("left_context", "right_context"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.new_clause_connective",
        "new-clause connective stranded at previous cue end",
        "grammar",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tokens",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.interrogative_complement",
        "interrogative complement separated after 'what'",
        "grammar",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("semantic_left_tail", "right_case"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.standalone_of_phrase",
        "standalone 'of' phrase separated from its governing noun",
        "grammar",
        BoundaryScoreDirection.RISK,
        32,
        ("en",),
        ("monologue", "dialogue"),
        ("right_clause",),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.clause_final_subject",
        "clause-final subject separated from its finite predicate",
        "grammar",
        BoundaryScoreDirection.RISK,
        40,
        ("en",),
        ("monologue", "dialogue"),
        ("left_clause", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.observation.lowercase_continuation_bonus",
        "lowercase continuation risk bonus",
        "observation",
        BoundaryScoreDirection.RISK,
        4,
        ("en",),
        ("monologue", "dialogue"),
        ("existing_risk", "right_case"),
    ),
)

_ENGLISH_COMPARISON_RULES = (
    BoundaryScoreRule(
        "split.boundary.english.comparison.clause_after_than",
        "comparative clause separated after 'than'",
        "comparison",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_clause"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.comparison.noun_phrase_before_than",
        "comparative noun phrase separated before 'than'",
        "comparison",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_comparative", "right_than_phrase"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.comparison.scalar_predicate",
        "scalar predicate separated from its comparative complement",
        "comparison",
        BoundaryScoreDirection.RISK,
        40,
        ("en",),
        ("monologue", "dialogue"),
        ("left_predicate", "right_comparative"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.comparison.frame_object",
        "comparison frame separated from its object",
        "comparison",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_frame", "right_object"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.comparison.repeated_degree",
        "repeated degree phrase split inside 'more and more'",
        "comparison",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_tokens"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.comparison.same_as",
        "comparison split between 'same' and 'as'",
        "comparison",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.comparison.frame_counterpart",
        "comparison frame separated from its counterpart",
        "comparison",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_frame", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.comparison.negated_complement",
        "negated comparison split from its complement",
        "comparison",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_negated_frame", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.comparison.dynamic_complement",
        "comparison complement split before '{token}'",
        "comparison",
        BoundaryScoreDirection.RISK,
        32,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.comparison.example",
        "comparative marker separated from its example",
        "comparison",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_entity"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.comparison.auxiliary_after_already",
        "comparison auxiliary separated after 'already'",
        "comparison",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_comparison", "right_auxiliary"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.entity.alphanumeric_model_alternative",
        "alphanumeric model alternative split before 'or'",
        "entity",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_head"),
    ),
)

_ENGLISH_COORDINATION_RULES = (
    BoundaryScoreRule(
        "split.boundary.english.coordination.relative_clause_subject",
        "coordinated relative-clause subject separated from its predicate",
        "coordination",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_clause", "right_predicate"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.coordination.paired_contrast",
        "paired contrast frame split before its counterpart",
        "coordination",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_frame", "right_counterpart"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.coordination.directional_names",
        "paired directional names split at conjunction",
        "coordination",
        BoundaryScoreDirection.RISK,
        40,
        ("en",),
        ("monologue", "dialogue"),
        ("left_entity", "right_entity"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.coordination.short_predicate_continuation",
        "short predicate separated from its coordinated continuation",
        "coordination",
        BoundaryScoreDirection.RISK,
        30,
        ("en",),
        ("monologue", "dialogue"),
        ("left_predicate", "right_continuation"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.coordination.automotive_intake_exhaust",
        "coordinate automotive term split between intake and exhaust",
        "coordination",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_tokens"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.coordination.reported_subject_member",
        "compound member split inside a coordinated reported subject",
        "coordination",
        BoundaryScoreDirection.RISK,
        40,
        ("en",),
        ("monologue", "dialogue"),
        ("left_reported_subject", "right_member"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.coordination.subject_predicate",
        "coordinated subject separated from its predicate",
        "coordination",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_subject", "right_predicate"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.coordination.noun_subject_shared_predicate",
        "coordinated noun subject split before its shared predicate",
        "coordination",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_noun_subject", "right_predicate"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.coordination.final_noun_progressive_predicate",
        "final coordinated noun separated with its progressive predicate",
        "coordination",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_noun_list", "right_progressive_predicate"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.coordination.omitted_subject_predicate",
        "omitted subject separated from its coordinated predicate",
        "coordination",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_clause", "right_coordinated_predicate"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.coordination.noun_list_progressive_predicate",
        "coordinated noun list separated from its progressive predicate",
        "coordination",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_noun_list", "right_progressive_predicate"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.coordination.what_clause_predicate",
        "coordinated predicate separated inside a what-clause",
        "coordination",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_what_clause", "right_predicate"),
    ),
)

_ENGLISH_ENTITY_RULES = (
    BoundaryScoreRule(
        "split.boundary.english.entity.powertrain_vehicle_name",
        "powertrain modifier separated from its vehicle name",
        "entity",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_powertrain_modifier", "right_vehicle_name"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.entity.vehicle_brand_model",
        "vehicle brand '{token}' separated from its model or type",
        "entity",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_vehicle_type"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.entity.city_state",
        "place name split between city and state",
        "entity",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_city", "right_state"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.entity.vehicle_trim_model",
        "vehicle trim separated from model name",
        "entity",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_trim", "right_model"),
    ),
)

_ENGLISH_DISCOURSE_RULES = (
    BoundaryScoreRule(
        "split.boundary.english.discourse.filler_demonstrative_noun",
        "filler separated from the demonstrative head noun",
        "discourse",
        BoundaryScoreDirection.RISK,
        40,
        ("en",),
        ("monologue", "dialogue"),
        ("left_filler", "right_demonstrative_noun"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.discourse.standalone_bridge",
        "standalone discourse bridge belongs to the following clause",
        "discourse",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_bridge", "right_clause"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.discourse.filler_only_frame",
        "filler-only discourse frame belongs to the following clause",
        "discourse",
        BoundaryScoreDirection.RISK,
        40,
        ("en",),
        ("monologue", "dialogue"),
        ("left_filler_frame", "right_clause"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.discourse.sentence_opening_filler",
        "sentence-opening filler belongs to the next cue",
        "discourse",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_filler", "right_clause"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.discourse.incomplete_predicate_before_filler",
        "incomplete predicate before trailing discourse filler",
        "discourse",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_predicate", "left_trailing_filler", "right_clause"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.discourse.predicate_after_modifier_strong",
        "predicate separated after a discourse modifier",
        "discourse",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_modifier", "right_predicate"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.discourse.predicate_after_modifier",
        "predicate separated after a discourse modifier",
        "discourse",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_modifier", "right_predicate"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.discourse.sentence_opening_opinion",
        "sentence-opening opinion marker belongs to the next cue",
        "discourse",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_opinion_marker", "right_clause"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.discourse.parenthetical_opinion",
        "parenthetical opinion separated from its governing clause",
        "discourse",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_parenthetical", "right_clause"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.discourse.standalone_opinion",
        "standalone opinion marker belongs to the following clause",
        "discourse",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_opinion_marker", "right_clause"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.discourse.transitive_predicate_before_filler",
        "transitive predicate separated before trailing discourse filler",
        "discourse",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_predicate", "left_trailing_filler", "right_object"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.discourse.frame_following_clause",
        "discourse frame separated from its following clause",
        "discourse",
        BoundaryScoreDirection.RISK,
        30,
        ("en",),
        ("monologue", "dialogue"),
        ("left_frame", "right_clause"),
    ),
)

_ENGLISH_GRAMMAR_EXTENSION_RULES = (
    BoundaryScoreRule(
        "split.boundary.english.grammar.adverb_gerund",
        "adverb separated from its gerund",
        "grammar",
        BoundaryScoreDirection.RISK,
        32,
        ("en",),
        ("monologue", "dialogue"),
        ("left_adverb", "right_gerund"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.time_frame_participle",
        "time frame separated from its defining participial phrase",
        "grammar",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_time_frame", "right_participle"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.frequency_quantified_statement",
        "frequency phrase separated from its quantified statement",
        "grammar",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_quantified_statement", "right_frequency"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.distance_location_noun",
        "distance modifier separated from its location noun",
        "grammar",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_distance", "right_location"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.determiner_degree_modifier_head",
        "determiner and degree modifier separated from their head noun",
        "grammar",
        BoundaryScoreDirection.RISK,
        40,
        ("en",),
        ("monologue", "dialogue"),
        ("left_determiner_degree", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.preposition_gerund",
        "preposition separated from its gerund phrase",
        "grammar",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_preposition", "right_gerund"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.hyphenated_attributive",
        "hyphenated attributive '{token}' separated from its noun",
        "grammar",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_hyphenated_tail", "right_noun"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.expect_to_always",
        "open continuation after 'expect to always'",
        "grammar",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_open_continuation", "right_predicate"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.quantifying_phrase_noun",
        "quantifying phrase separated from its noun",
        "grammar",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_quantifier", "right_noun"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.degree_so",
        "degree phrase split inside 'so {token}'",
        "grammar",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.up_and_running",
        "fixed state phrase split inside 'up and running'",
        "grammar",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_tokens"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.up_and_running_aspect",
        "aspect marker split from 'up and running'",
        "grammar",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_tokens"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.phrasal_verb",
        "split phrasal verb '{left} {right}'",
        "grammar",
        BoundaryScoreDirection.RISK,
        32,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.take_away",
        "split phrasal construction 'take ... away'",
        "grammar",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_take_frame", "right_away"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.sentence_opening_time_marker",
        "sentence-opening time marker belongs to the next cue",
        "grammar",
        BoundaryScoreDirection.RISK,
        36,
        ("en",),
        ("monologue", "dialogue"),
        ("left_time_marker", "right_clause"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.do_not_get_me_wrong",
        "fixed phrase split inside 'do not get me wrong'",
        "grammar",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_fixed_phrase", "right_article"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.sentence_opening_time_adverb",
        "sentence-opening time adverb belongs to the next cue",
        "grammar",
        BoundaryScoreDirection.RISK,
        30,
        ("en",),
        ("monologue", "dialogue"),
        ("left_time_adverb", "right_clause"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.contrastive_beneficiary",
        "contrastive beneficiary phrase belongs to the next cue",
        "grammar",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_beneficiary", "right_clause"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.lexical_unit",
        "split lexical unit '{left} {right}'",
        "grammar",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.direction_here",
        "directional phrase split inside '{token} here'",
        "grammar",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_tail", "right_head"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.context_dependent_adjective",
        "context-dependent adjective separated from its continuation",
        "grammar",
        BoundaryScoreDirection.RISK,
        32,
        ("en",),
        ("monologue", "dialogue"),
        ("left_adjective", "right_continuation"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.reporting_copular_content",
        "reporting frame separated from its copular content",
        "grammar",
        BoundaryScoreDirection.RISK,
        38,
        ("en",),
        ("monologue", "dialogue"),
        ("left_reporting_frame", "right_copular_content"),
    ),
    BoundaryScoreRule(
        "split.boundary.english.grammar.temporal_continuation",
        "temporal phrase separated from its continuation",
        "grammar",
        BoundaryScoreDirection.RISK,
        34,
        ("en",),
        ("monologue", "dialogue"),
        ("left_temporal_phrase", "right_continuation"),
    ),
)


def _english_predicate_rule(
    rule_id: str,
    reason: str,
    weight: int,
    required_features: tuple[str, ...],
    exclusions: tuple[str, ...] = (),
) -> BoundaryScoreRule:
    return BoundaryScoreRule(
        rule_id,
        reason,
        "predicate",
        BoundaryScoreDirection.RISK,
        weight,
        ("en",),
        ("monologue", "dialogue"),
        required_features,
        exclusions,
    )


_ENGLISH_PREDICATE_RULES = (
    _english_predicate_rule(
        "split.boundary.english.predicate.subject_adverb",
        "subject and adverb separated from its predicate",
        36,
        ("left_subject_adverb", "right_predicate"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.negative_auxiliary_complement",
        "negative auxiliary is separated from its complement",
        36,
        ("left_negative_auxiliary", "right_complement"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.linking_verb_complement",
        "linking verb separated from its complement",
        38,
        ("left_linking_verb", "right_complement"),
        ("interrogative_subject",),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.progressive_complement",
        "progressive predicate separated from its complement",
        32,
        ("left_progressive_predicate", "right_complement"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.auxiliary_participle",
        "auxiliary phrase separated from its participle",
        38,
        ("left_auxiliary_phrase", "right_participle"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.sentence_adverb_finite",
        "sentence adverb separated from its finite predicate",
        34,
        ("left_sentence_adverb", "right_finite_predicate"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.auxiliary_sentence_adverb",
        "auxiliary and sentence adverb separated from their predicate",
        38,
        ("left_auxiliary_adverb", "right_predicate"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.infinitive_adverb",
        "infinitive adverb separated from its predicate",
        38,
        ("left_infinitive_adverb", "right_predicate"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.participle_quantified_object",
        "transitive participle separated from its quantified object",
        38,
        ("left_transitive_participle", "right_quantified_object"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.modal_adverb",
        "modal adverb separated from its predicate",
        38,
        ("left_modal_adverb", "right_predicate"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.contrastive_prepositional_frame",
        "contrastive prepositional frame separated from its main clause",
        38,
        ("left_contrastive_frame", "right_main_clause"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.sentence_final_temporal_adverb",
        "sentence-final temporal adverb separated from its clause",
        40,
        ("left_clause", "right_temporal_adverb"),
        ("terminal_left",),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.reporting_quoted_object",
        "reporting predicate separated from its quoted object",
        36,
        ("left_reporting_predicate", "right_quoted_object"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.prepositional_gerund_complement",
        "prepositional gerund separated from its complement",
        36,
        ("left_prepositional_gerund", "right_complement"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.condition_qualified_predicate",
        "condition separated from the predicate it qualifies",
        32,
        ("left_condition", "right_predicate"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.relative_clause_subject",
        "relative-clause subject separated from its predicate",
        34,
        ("left_relative_subject", "right_predicate"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.progressive_object",
        "progressive predicate separated from its object",
        36,
        ("left_progressive_predicate", "right_object"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.topic_frame",
        "topic frame separated from its following predicate",
        38,
        ("left_topic_frame", "right_predicate"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.up_and_running_subject",
        "state predicate 'up and running' separated from its subject",
        38,
        ("left_state_predicate", "right_subject"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.short_noun_subject",
        "short noun subject separated from its predicate",
        34,
        ("left_short_subject", "right_predicate"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.subject_complement",
        "subject complement split before '{head}'",
        28,
        ("left_subject_frame", "right_complement"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.omitted_relative_one",
        "omitted relative clause separated from 'one'",
        24,
        ("left_one", "right_omitted_relative"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.copula_parenthetical_complement",
        "copula separated from its complement by a parenthetical",
        30,
        ("left_copula_parenthetical", "right_complement"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.emphatic_inversion_complement",
        "emphatic inversion separated from its complement",
        40,
        ("left_emphatic_inversion", "right_complement"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.standalone_contrast_frame",
        "standalone contrast frame belongs to the following clause",
        40,
        ("left_contrast_frame", "right_clause"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.negative_existential_complement",
        "negative existential separated from its complement",
        36,
        ("left_negative_existential", "right_complement"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.reason_clause_subject",
        "reason clause opener separated from its subject",
        36,
        ("left_reason_opener", "right_subject"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.what_is_so_complement",
        "'what is so' complement split",
        36,
        ("left_what_is_so", "right_complement"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.transitive_object_basic",
        "transitive predicate separated from its object",
        34,
        ("left_transitive_predicate", "right_object"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.transitive_object_extended",
        "transitive predicate separated from its object",
        36,
        ("left_transitive_predicate", "right_object"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.perfect_reporting_content",
        "perfect reporting predicate separated from its content",
        36,
        ("left_perfect_reporting_predicate", "right_content"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.transitive_pronoun_object",
        "transitive predicate separated from its pronoun object",
        36,
        ("left_transitive_predicate", "right_pronoun_object"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.perfect_reporting_after_adverb",
        "perfect reporting predicate separated after its adverb",
        36,
        ("left_perfect_reporting_adverb", "right_content"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.reporting_content",
        "reporting predicate separated from its content",
        34,
        ("left_reporting_predicate", "right_content"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.embedded_question_complement",
        "embedded question frame separated from its complement",
        36,
        ("left_embedded_question", "right_complement"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.reported_subject",
        "reported subject separated from its predicate",
        34,
        ("left_reported_subject", "right_predicate"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.transitive_nominal_clause",
        "transitive predicate separated from its nominal clause",
        36,
        ("left_transitive_predicate", "right_nominal_clause"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.what_use_for_object",
        "object split inside 'what ... use ... for' construction",
        36,
        ("left_what_use", "right_object_for"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.dependent_locative_clause",
        "dependent locative phrase separated from its clause",
        30,
        ("left_clause", "right_locative_phrase"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.way_clause_subject",
        "way-clause subject separated from its predicate",
        32,
        ("left_way_subject", "right_predicate"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.proper_name_subject",
        "proper-name subject separated from its predicate",
        34,
        ("left_proper_name_subject", "right_predicate"),
        ("dependent_phrase",),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.trailing_noun_subject",
        "trailing noun subject separated from its finite predicate",
        38,
        ("left_trailing_subject", "right_finite_predicate"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.gerund_subject",
        "gerund subject separated from its finite predicate",
        38,
        ("left_gerund_subject", "right_finite_predicate"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.what_clause_subject",
        "what-clause subject separated from its predicate",
        36,
        ("left_what_clause", "right_predicate"),
    ),
    _english_predicate_rule(
        "split.boundary.english.predicate.degree_complement",
        "degree complement separated from its predicate",
        30,
        ("left_predicate", "right_degree_complement"),
    ),
)

BOUNDARY_SCORE_RULES = (
    *_ENGLISH_NUMERIC_RULES,
    *_ENGLISH_GRAMMAR_RULES,
    *_ENGLISH_COMPARISON_RULES,
    *_ENGLISH_COORDINATION_RULES,
    *_ENGLISH_ENTITY_RULES,
    *_ENGLISH_DISCOURSE_RULES,
    *_ENGLISH_GRAMMAR_EXTENSION_RULES,
    *_ENGLISH_PREDICATE_RULES,
)
_BOUNDARY_SCORE_RULE_BY_ID = {rule.rule_id: rule for rule in BOUNDARY_SCORE_RULES}

if len(_BOUNDARY_SCORE_RULE_BY_ID) != len(BOUNDARY_SCORE_RULES):
    raise RuntimeError("Duplicate boundary score rule ID")


def boundary_score_rule(rule_id: str) -> BoundaryScoreRule:
    try:
        return _BOUNDARY_SCORE_RULE_BY_ID[rule_id]
    except KeyError as exc:
        raise ValueError(f"Unregistered boundary score rule: {rule_id}") from exc


def record_boundary_score(
    rule_id: str,
    *,
    reasons: list[str],
    contributions: list[BoundaryScoreContribution],
    reason_values: dict[str, str] | None = None,
    append_reason: bool = True,
) -> int:
    """Record one legacy-equivalent score contribution and return its weight."""
    rule = boundary_score_rule(rule_id)
    reason = rule.reason.format_map(reason_values or {})
    if append_reason:
        reasons.append(reason)
    contributions.append(
        BoundaryScoreContribution(
            rule_id=rule.rule_id,
            reason=reason,
            weight=rule.weight,
        )
    )
    return rule.weight
